# Generated by Django 4.2.5 on 2023-09-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('min_deposit', models.CharField(max_length=16)),
                ('min_withdraw', models.CharField(max_length=16)),
                ('profit_description', models.CharField(max_length=64)),
                ('affiliate_program', models.CharField(max_length=16)),
                ('insurance', models.DecimalField(decimal_places=2, max_digits=7)),
                ('currency', models.CharField(max_length=8)),
                ('our_deposit', models.DecimalField(decimal_places=2, max_digits=7)),
                ('our_withdraw', models.DecimalField(decimal_places=2, max_digits=7)),
                ('youtube_link', models.URLField()),
                ('withdraw_type', models.CharField(choices=[('INS', 'Instant'), ('MAN', 'Manual')], max_length=4)),
                ('profit_type', models.CharField(choices=[('H', 'Highly profitable'), ('M', 'Middle profitable'), ('L', 'Low profitable')], max_length=2)),
                ('is_scam', models.BooleanField(default=True)),
                ('started_at', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
